name: 通过 GitHub Pages 部署网站
on:
  push:
    branches:
      - 'file'

    paths-ignore:
      - 'README.md'

  pull_request:
    branches:
      - 'file'

    paths-ignore:
      - 'README.md'

  workflow_dispatch: # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 获取完整历史记录，以便能够推送回仓库
          fetch-depth: 0

      - name: 安装 NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Run generate-index script
        run: |
          node assets/scripts/generate-index.js

      - name: 检查更改
        id: git-check
        run: |
          echo "检查是否有文件被修改..."
          if git diff --quiet; then
            echo "没有检测到更改"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件更改"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 配置 Git
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "42103905+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: 提交更改
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "自动生成索引文件 [skip ci]"
          git push

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 上传页面
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署页面
        id: deployment
        uses: actions/deploy-pages@v4
